[build]
  # 빌드 명령어
  command = "npm run build"

  # 빌드 결과물이 생성되는 디렉토리
  publish = "dist"

# 리다이렉트 설정 (SPA를 위한 설정)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수 (Netlify 대시보드에서 설정 필요)
# VITE_FIREBASE_API_KEY
# VITE_FIREBASE_AUTH_DOMAIN
# VITE_FIREBASE_PROJECT_ID
# VITE_FIREBASE_STORAGE_BUCKET
# VITE_FIREBASE_MESSAGING_SENDER_ID
# VITE_FIREBASE_APP_ID
